services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  relay-1:
    build:
      context: ..
      dockerfile: relay-node/Dockerfile
    container_name: relay-1
    environment:
      - NODE_ID=relay-1
      - NODE_HOST=relay-1
      - API_PORT=7070
      - AUDIO_PORT=5002
      - VIDEO_PORT=5004
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "7070:7070"
      - "5002:5002/udp"
      - "5004:5004/udp"
    depends_on:
      - redis
