services:
  # ============ INFRA ============

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - media-tree

  # ============ JANUS ============

  janus-videoroom:
    build:
      context: ./janus-videoroom
      dockerfile: Dockerfile
    container_name: janus-videoroom
    ports:
      - "8088:8088"
      - "8188:8188"
      - "20000-20050:20000-20050/udp"
    volumes:
      - ./janus-videoroom/config:/opt/janus/etc/janus:ro
    environment:
      - JANUS_LOG_LEVEL=4
    networks:
      - media-tree

  janus-streaming-1:
    build:
      context: ./janus-streaming
      dockerfile: Dockerfile
    container_name: janus-streaming-1
    ports:
      - "8089:8088" # HTTP API
      - "8189:8188" # WebSocket
      - "6002:5002/udp" # RTP Audio
      - "6004:5004/udp" # RTP Video
      - "20051-20150:20051-20150/udp"
    volumes:
      - ./janus-streaming/config:/opt/janus/etc/janus:ro
    environment:
      - JANUS_LOG_LEVEL=4
    networks:
      - media-tree

  janus-streaming-2:
    build:
      context: ./janus-streaming
      dockerfile: Dockerfile
    container_name: janus-streaming-2
    ports:
      - "8190:8188" # WebSocket
      - "8090:8088" # HTTP API
      - "7002:5002/udp" # RTP Audio
      - "7004:5004/udp" # RTP Video
      - "20151-20200:20101-20150/udp" # WebRTC
    volumes:
      - ./janus-streaming/config:/opt/janus/etc/janus:ro
    environment:
      - JANUS_LOG_LEVEL=4
    networks:
      - media-tree
    profiles:
      - scale
  # ============ INJECTION NODE ============

  injection-1:
    build:
      context: .
      dockerfile: injection-node/Dockerfile
    container_name: injection-1
    ports:
      - "7070:7070"
    environment:
      - NODE_ID=injection-1
      - NODE_HOST=injection-1
      - NODE_PORT=7070
      - RTP_AUDIO_PORT=5000
      - RTP_VIDEO_PORT=5002
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JANUS_VIDEOROOM_WS_URL=ws://janus-videoroom:8188
      - WHIP_BASE_PATH=/whip
      - WHIP_TOKEN=verysecret
      - WHIP_SECRET=adminpwd
    depends_on:
      - redis
      - janus-videoroom
    networks:
      - media-tree

  # ============ RELAY NODES ============

  relay-gst-1:
    build:
      context: .
      dockerfile: relay-node-gstreamer/Dockerfile
    container_name: relay-gst-1
    environment:
      - NODE_ID=relay-gst-1
      - NODE_HOST=relay-gst-1
      - API_PORT=7071
      - AUDIO_PORT=5002
      - VIDEO_PORT=5004
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "7071:7071"
      - "5002:5002/udp"
      - "5004:5004/udp"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - media-tree

  relay-gst-2:
    build:
      context: .
      dockerfile: relay-node-gstreamer/Dockerfile
    container_name: relay-gst-2
    environment:
      - NODE_ID=relay-gst-2
      - NODE_HOST=relay-gst-2
      - API_PORT=7072
      - AUDIO_PORT=5102
      - VIDEO_PORT=5104
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "7072:7072"
      - "5102:5102/udp"
      - "5104:5104/udp"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - media-tree
    profiles:
      - relay-switch

  # ============ EGRESS NODE ============

  egress-1:
    build:
      context: .
      dockerfile: egress-node/Dockerfile
    container_name: egress-1
    ports:
      - "7073:7073"
    environment:
      - NODE_ID=egress-1
      - NODE_HOST=egress-1
      - API_PORT=7073
      - RTP_AUDIO_PORT=5002
      - RTP_VIDEO_PORT=5004
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JANUS_STREAMING_WS_URL=ws://janus-streaming:8188
      - WHEP_BASE_PATH=/whep
      - WHEP_TOKEN=verysecret
    depends_on:
      - redis
      - janus-streaming-1
    networks:
      - media-tree

  egress-2:
    build:
      context: .
      dockerfile: egress-node/Dockerfile
    container_name: egress-2
    ports:
      - "7074:7074"
    environment:
      - NODE_ID=egress-2
      - NODE_HOST=egress-2
      - API_PORT=7074
      - RTP_AUDIO_PORT=5002
      - RTP_VIDEO_PORT=5004
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JANUS_STREAMING_WS_URL=ws://janus-streaming-2:8188
      - WHEP_BASE_PATH=/whep
      - WHEP_TOKEN=verysecret
    depends_on:
      - redis
      - janus-streaming-2
    networks:
      - media-tree
    profiles:
      - scale
  ## ============ RTP RECEIVER ============
  #
  #receiver-1:
  #  build: ./relay-node-gstreamer/test
  #  container_name: rtp-receiver-gst-1
  #  environment:
  #    - MODE=receiver
  #    - LISTEN_AUDIO_PORT=6000
  #    - LISTEN_VIDEO_PORT=6002
  #    - GST_DEBUG=2
  #  ports:
  #    - "6000:6000/udp"
  #    - "6002:6002/udp"
  #  networks:
  #    - media-tree

  # ============ WHIP CLIENT ============

  whip-client:
    build:
      context: ./simple-whip-client
      dockerfile: Dockerfile
    container_name: whip-client
    environment:
      - URL=http://injection-1:7070/whip/endpoint/live-session
      - TOKEN=verysecret
      - AUDIO_PIPE=audiotestsrc is-live=true wave=sine freq=440 ! audioconvert ! audioresample ! queue ! opusenc ! rtpopuspay pt=111 ssrc=1 ! queue ! application/x-rtp,media=audio,encoding-name=OPUS,payload=111
      - VIDEO_PIPE=videotestsrc is-live=true pattern=ball ! video/x-raw,width=640,height=480,framerate=30/1 ! videoconvert ! queue ! vp8enc deadline=1 ! rtpvp8pay pt=96 ssrc=2 ! queue ! application/x-rtp,media=video,encoding-name=VP8,payload=96
      - STUN_SERVER=stun://stun.l.google.com:19302
      - GST_DEBUG=2
    depends_on:
      - injection-1
    networks:
      - media-tree
    profiles:
      - streaming

networks:
  media-tree:
    driver: bridge
